In [12]:
from PIL import Image
import numpy as np
# image a liste (RGB) (cette methode cree une liste de liste)
im = Image.open("/Users/roulaabifadel/Downloads/pika.png")
#print(im.format, im.size, im.mode)
#im.show()
na = np.array(im)
print(na)

[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]


In [8]:
# image a liste (RGBA) (cette mnethode cree une liste de tuples)
image_with_alpha = Image.open("/Users/roulaabifadel/Downloads/listimage_binary.png")
# mettre en mode RGBA 
image_with_alpha = image_with_alpha.convert('RGBA')

# connvertir l'image a une liste de tuples (R, G, B, A)
pixels_list_with_alpha = list(image_with_alpha.getdata())

pixels_list_with_alpha


[(255, 0, 0, 255),
 (0, 255, 0, 255),
 (0, 0, 255, 255),
 (0, 0, 0, 255),
 (255, 255, 255, 255),
 (126, 126, 126, 255)]

In [ ]:
import numpy as np
from PIL import Image
#list a image RGB
pixel_list = [
    [[255, 0, 0], [0, 255, 0], [0, 0, 255]],
    [[0, 0, 0], [255, 255, 255], [126, 126, 126]]
]
# ou on peut faire
binary_pixel_list = [
    [[0b11111111, 0b0, 0b0], [0b0, 0b11111111, 0b0], [0b0, 0b0, 0b11111111]],
    [[0b0, 0b0, 0b0], [0b11111111, 0b11111111, 0b11111111], [0b1111110, 0b1111110, 0b1111110]]
]
np_array = np.array(pixel_list, dtype=np.uint8) #convert to numpy array
image = Image.fromarray(np_array) #use numpy to create image
image.save('listimage.png') #save

In [11]:
import numpy as np
from PIL import Image
#meme chose mais avec transparency RGBA
binary_pixel_list_rgba = [
    [[0b11111111, 0b0, 0b0, 0b10000000], [0b0, 0b11111111, 0b0, 0b10000000], [0b0, 0b0, 0b11111111, 0b10000000]],
    [[0b0, 0b0, 0b0, 0b10000000], [0b11111111, 0b11111111, 0b11111111, 0b10000000], [0b1111110, 0b1111110, 0b1111110, 0b10000000]]
]

np_array_binary_rgba = np.array(binary_pixel_list_rgba, dtype=np.uint8)

image_binary_rgba = Image.fromarray(np_array_binary_rgba, 'RGBA')

image_binary_rgba.save('listimage_binary_rgba.png')

